name: persona
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - transformers
  - pytorch
  - scikit-learn
  - python-dotenv
  # - ipykernel
  - pip:
      - accelerate==1.13.0
      - torch==2.4.1
      - torchvision==0.19.1
      - flash-attn --no-build-isolation