name: persona
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - transformers
  - pytorch
  - scikit-learn
  # - ipykernel
  # - pip:
  #     - transformers
  #     - langchain